language: ruby
script: 'rspec spec'
before_install:
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start
env:
  - CASSANDRA_HOST=127.0.0.1
rvm:
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk7
